unit TestUItensRateioVO;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, SysUtils, Atributos, UUnidadeVO, Generics.Collections, UGenericVO,
  Classes, Constantes, UItensRateioVO;

type
  // Test methods for class TItensRateioVO

  TestTItensRateioVO = class(TTestCase)
  strict private
    FItensRateioVO: TItensRateioVO;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestValidarCamposObrigatorios;
    procedure TestValidarCamposObrigatoriosNaoEncontrado;
  end;

implementation

procedure TestTItensRateioVO.SetUp;
begin
  FItensRateioVO := TItensRateioVO.Create;
end;

procedure TestTItensRateioVO.TearDown;
begin
  FItensRateioVO.Free;
  FItensRateioVO := nil;
end;

procedure TestTItensRateioVO.TestValidarCamposObrigatorios;
var
  Rateio : TItensRateioVO;
begin
  Rateio := TItensRateioVO.Create;
  Rateio.dtRateio := StrToDate('01/01/2016');
  Rateio.vlRateio := 10;
  try
     Rateio.ValidarCamposObrigatorios;
     Check(True,'Sucesso!')
  except on E: Exception do
     Check(false,'Erro!');
  end;
end;

procedure TestTItensRateioVO.TestValidarCamposObrigatoriosNaoEncontrado;
var
  Rateio : TItensRateioVO;
begin
  Rateio := TItensRateioVO.Create;
  Rateio.vlRateio := 10;
  try
     Rateio.ValidarCamposObrigatorios;
     Check(false,'Erro!')
  except on E: Exception do
     Check(True,'Sucesso!');
  end;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTItensRateioVO.Suite);
end.

