unit TestUHistoricoVO;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, SysUtils, Atributos, Generics.Collections, UGenericVO, Classes,
  Constantes, UHistoricoVO;

type
  // Test methods for class THistoricoVO

  TestTHistoricoVO = class(TTestCase)
  strict private
    FHistoricoVO: THistoricoVO;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestValidarCamposObrigatorios;
    procedure TestValidarCamposObrigatoriosNaoEncontrado;
  end;

implementation

procedure TestTHistoricoVO.SetUp;
begin
  FHistoricoVO := THistoricoVO.Create;
end;

procedure TestTHistoricoVO.TearDown;
begin
  FHistoricoVO.Free;
  FHistoricoVO := nil;
end;

procedure TestTHistoricoVO.TestValidarCamposObrigatorios;
var
  Historico : THistoricoVO;
begin
  Historico := THistoricoVo.Create;
  Historico.FlContaCorrente := '0';
  Historico.DsHistorico :='Teste';

  try
     Historico.ValidarCamposObrigatorios;
     Check(true,'Sucesso!')
  except on E: Exception do
     Check(false,'Erro!');
  end;
end;

procedure TestTHistoricoVO.TestValidarCamposObrigatoriosNaoEncontrado;
var
  Historico : THistoricoVO;
begin
  Historico := THistoricoVo.Create;
  Historico.FlContaCorrente := '0';
  Historico.DsHistorico :='';

  try
     Historico.ValidarCamposObrigatorios;
     Check(false,'Erro!')
  except on E: Exception do
     Check(true,'Sucesso!');
  end;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTHistoricoVO.Suite);
end.

