unit TestUItensLeituraGasVO;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, SysUtils, Atributos, UUnidadeVO, Generics.Collections, UGenericVO,
  Classes, Constantes, UItensLeituraGasVO;

type
  // Test methods for class TItensLeituraGasVO

  TestTItensLeituraGasVO = class(TTestCase)
  strict private
    FItensLeituraGasVO: TItensLeituraGasVO;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestValidarCamposObrigatorios;
    procedure TestValidarCamposObrigatoriosNaoEncontrado;
  end;

implementation

procedure TestTItensLeituraGasVO.SetUp;
begin
  FItensLeituraGasVO := TItensLeituraGasVO.Create;
end;

procedure TestTItensLeituraGasVO.TearDown;
begin
  FItensLeituraGasVO.Free;
  FItensLeituraGasVO := nil;
end;

procedure TestTItensLeituraGasVO.TestValidarCamposObrigatorios;
var
  Leitura : TItensLeituraGasVO;
begin
  Leitura := TItensLeituraGasVO.Create;
  Leitura.dtLeitura := StrToDate('01/01/2016');
  Leitura.vlMedido := 1;
  try
     Leitura.ValidarCamposObrigatorios;
     Check(True,'Sucesso!')
  except on E: Exception do
     Check(false,'Erro!');
  end;
end;

procedure TestTItensLeituraGasVO.TestValidarCamposObrigatoriosNaoEncontrado;
var
  Leitura : TItensLeituraGasVO;
begin
  Leitura := TItensLeituraGasVO.Create;
  Leitura.dtLeitura := StrToDate('01/01/2016');
  Leitura.vlMedido := -1;
  try
     Leitura.ValidarCamposObrigatorios;
     Check(false,'Erro!')
  except on E: Exception do
     Check(true,'Sucesso!');
  end;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTItensLeituraGasVO.Suite);
end.

