unit TestUProprietarioUnidadeController;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UCondominioVO, SysUtils, DBClient, DBXJSON, UPessoasVO,
  UCondominioController, DBXCommon, UProprietarioUnidadeController,
  UPessoasCOntroller, Generics.Collections, Classes, UController, DB,
  UProprietarioUnidadeVO, ConexaoBD, SQLExpr;

type
  // Test methods for class TProprietarioUnidadeController

  TestTProprietarioUnidadeController = class(TTestCase)
  strict private
    FProprietarioUnidadeController: TProprietarioUnidadeController;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestConsultarPorId;
  end;

implementation

procedure TestTProprietarioUnidadeController.SetUp;
begin
  FProprietarioUnidadeController := TProprietarioUnidadeController.Create;
end;

procedure TestTProprietarioUnidadeController.TearDown;
begin
  FProprietarioUnidadeController.Free;
  FProprietarioUnidadeController := nil;
end;

procedure TestTProprietarioUnidadeController.TestConsultarPorId;
var
  ReturnValue: TProprietarioUnidadeVO;
 // id: Integer;
begin
  ReturnValue := FProprietarioUnidadeController.ConsultarPorId(10);
  if(returnvalue <> nil)  then
    check(true,'Proprietário pesquisado com sucesso!')
  else
    check(false,'Proprietário não encontrado!');

end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTProprietarioUnidadeController.Suite);
end.

