unit TestUPessoasController;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, DB, DBXJSON, ConexaoBD, Generics.Collections, UController, Classes,
  UPessoasController, SysUtils, DBClient, UPessoasVO, UCnaeVO, DBXCommon, SQLExpr,
  UCidadeVO;

type
  // Test methods for class TPessoasController

  TestTPessoasController = class(TTestCase)
  strict private
    FPessoasController: TPessoasController;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestConsultarPorId;
  end;

implementation

procedure TestTPessoasController.SetUp;
begin
  FPessoasController := TPessoasController.Create;
end;

procedure TestTPessoasController.TearDown;
begin
  FPessoasController.Free;
  FPessoasController := nil;
end;

procedure TestTPessoasController.TestConsultarPorId;
var
  ReturnValue: TPessoasVO;
 // id: Integer;
begin
  ReturnValue := FPessoasController.ConsultarPorId(10);
  if(returnvalue <> nil)  then
    check(true,'Pessoa pesquisada com sucesso!')
  else
    check(false,'Pessoa nao encontrada!');

end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTPessoasController.Suite);
end.

