ALTER TABLE LeituraGas ADD CONSTRAINT PK_LeituraGas PRIMARY KEY (idLeituraGas);

ALTER TABLE Rateio ADD CONSTRAINT PK_Rateio PRIMARY KEY (idRateio);

ALTER TABLE ItensLeituraGas ADD CONSTRAINT PK_ItensLeituraGas PRIMARY KEY (idItensLeituraGas);

ALTER TABLE ItensRateio ADD CONSTRAINT PK_ItensRateio PRIMARY KEY (idItensRateio);

ALTER TABLE ItensLeituraGas ADD CONSTRAINT FK_ItensLeituraGas_0 FOREIGN KEY (idLeituraGas) REFERENCES LeituraGas (idLeituraGas);

ALTER TABLE ItensRateio ADD CONSTRAINT FK_ItensRateio_0 FOREIGN KEY (idRateio) REFERENCES Rateio (idRateio);

ALTER TABLE CONDOMINIO ADD IDCTJUROS INTEGER

ALTER TABLE CONDOMINIO ADD IDCTMULTA INTEGER

ALTER TABLE CONDOMINIO ADD IDCTDESCONTOREC INTEGER

ALTER TABLE CONDOMINIO ADD IDCTJUROSP INTEGER

ALTER TABLE CONDOMINIO ADD IDCTMULTAP INTEGER

ALTER TABLE CONDOMINIO ADD IDCTDESCONTOOBT INTEGER

ALTER TABLE CONDOMINIO ADD CONSTRAINT FK_CONDOMINIO_4 FOREIGN KEY (IDCTJUROS) REFERENCES PLANOCONTAS(IDPLANOCONTAS)

ALTER TABLE CONDOMINIO ADD CONSTRAINT FK_CONDOMINIO_5 FOREIGN KEY (IDCTMULTA) REFERENCES PLANOCONTAS(IDPLANOCONTAS)

ALTER TABLE CONDOMINIO ADD CONSTRAINT FK_CONDOMINIO_6 FOREIGN KEY (IDCTDESCONTOREC) REFERENCES PLANOCONTAS(IDPLANOCONTAS)

ALTER TABLE CONDOMINIO ADD CONSTRAINT FK_CONDOMINIO_7 FOREIGN KEY (IDCTJUROSP) REFERENCES PLANOCONTAS(IDPLANOCONTAS)

ALTER TABLE CONDOMINIO ADD CONSTRAINT FK_CONDOMINIO_8 FOREIGN KEY (IDCTMULTAP) REFERENCES PLANOCONTAS(IDPLANOCONTAS)

ALTER TABLE CONDOMINIO ADD CONSTRAINT FK_CONDOMINIO_9 FOREIGN KEY (IDCTDESCONTOOBT) REFERENCES PLANOCONTAS(IDPLANOCONTAS)

ALTER TABLE CONDOMINIO ADD IDHISTORICOL INTEGER

ALTER TABLE CONDOMINIO ADD CONSTRAINT FK_CONDOMINIO_13 FOREIGN KEY (IDHISTORICOL) REFERENCES HISTORICOS(IDHISTORICO)

ALTER TABLE CONDOMINIO ADD IDHISTORICOR INTEGER 

ALTER TABLE CONDOMINIO ADD CONSTRAINT FK_CONDOMINIO_14 FOREIGN KEY (IDHISTORICOR) REFERENCES HISTORICOS(IDHISTORICO)

ALTER TABLE CONDOMINIO ADD IDHISTORICOF INTEGER 

ALTER TABLE CONDOMINIO ADD CONSTRAINT FK_CONDOMINIO_15 FOREIGN KEY (IDHISTORICOF) REFERENCES HISTORICOS(IDHISTORICO)