unit TestUContasPagarController;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UContasPagarVO, UCondominioVO, SysUtils, DBClient, DBXJSON, UPessoasVO,
  UCondominioController, DBXCommon, UHistoricoVO, UPlanoCOntasController,
  UPessoasController, Generics.Collections, Classes, UController, DB, UPlanoContasVO,
  UContasPagarController, ConexaoBD, SQLExpr;

type
  // Test methods for class TContasPagarController

  TestTContasPagarController = class(TTestCase)
  strict private
    FContasPagarController: TContasPagarController;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestConsultarPorId;
    procedure TestConsultaPorIdNaoEncontrado;
  end;

implementation

procedure TestTContasPagarController.SetUp;
begin
  FContasPagarController := TContasPagarController.Create;
end;

procedure TestTContasPagarController.TearDown;
begin
  FContasPagarController.Free;
  FContasPagarController := nil;
end;

procedure TestTContasPagarController.TestConsultaPorIdNaoEncontrado;
var
  ReturnValue: TContasPagarVO;
  id: Integer;
begin
  ReturnValue := FContasPagarController.ConsultarPorId(150);
  if(returnvalue <> nil)  then
    check(false,'Contas a Pagar  pesquisado com sucesso!')
  else
    check(true,'Contas a Pagar não encontrado!');
end;

procedure TestTContasPagarController.TestConsultarPorId;
var
  ReturnValue: TContasPagarVO;
  id: Integer;
begin
  ReturnValue := FContasPagarController.ConsultarPorId(25);

  if(returnvalue <> nil)  then
    check(true,'Contas a Pagar  pesquisado com sucesso!')
  else
    check(false,'Contas a Pagar não encontrado!');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTContasPagarController.Suite);
end.

