unit TestUContasReceberController;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UCondominioVO, SysUtils, UPessoasController, DBXJSON, UPlanoContasVO,
  UCondominioController, DBXCommon, UHistoricoVO, DBClient, UPlanoCOntasController,
  UUnidadeVO, Generics.Collections, Classes, UController, UContasReceberVO, DB,
  UContasReceberController, ConexaoBD, SQLExpr;

type
  // Test methods for class TContasReceberController

  TestTContasReceberController = class(TTestCase)
  strict private
    FContasReceberController: TContasReceberController;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestConsultarPorId;
    procedure TestConsultaPorIdNaoEncontrado;
  end;

implementation

procedure TestTContasReceberController.SetUp;
begin
  FContasReceberController := TContasReceberController.Create;
end;

procedure TestTContasReceberController.TearDown;
begin
  FContasReceberController.Free;
  FContasReceberController := nil;
end;

procedure TestTContasReceberController.TestConsultaPorIdNaoEncontrado;
var
  ReturnValue: TContasReceberVO;
begin
  ReturnValue := FContasReceberController.ConsultarPorId(160);
  if ReturnValue <> nil then
    check(false,'Contas a Pagar  pesquisado com sucesso!')
  else
    check(true,'Contas a Pagar não encontrado!');
end;

procedure TestTContasReceberController.TestConsultarPorId;
var
  ReturnValue: TContasReceberVO;
begin
  ReturnValue := FContasReceberController.ConsultarPorId(28);
  if ReturnValue <> nil then
    check(true,'Contas a Pagar  pesquisado com sucesso!')
  else
    check(false,'Contas a Pagar não encontrado!');

end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTContasReceberController.Suite);
end.

