unit TestUItensRateioController;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UController, ULeituraGasVO, SysUtils, DBClient, DBXJSON, UItensRateioVo,
  UPessoasVO, UCondominioController, DBXCommon, UHistoricoVO, UPlanoCOntasController,
  UUnidadeVO, UPessoasController, Generics.Collections, Classes, UEmpresaTrab,
  UItensRateioController, DB, UPlanoContasVO, ULancamentoContabilVO, ConexaoBD, SQLExpr;

type
  // Test methods for class TItensRateioController

  TestTItensRateioController = class(TTestCase)
  strict private
    FItensRateioController: TItensRateioController;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestConsultarPorId;
    procedure TestConsultarPorIdNaoEncontrado;
  end;

implementation

procedure TestTItensRateioController.SetUp;
begin
  FItensRateioController := TItensRateioController.Create;
end;

procedure TestTItensRateioController.TearDown;
begin
  FItensRateioController.Free;
  FItensRateioController := nil;
end;

procedure TestTItensRateioController.TestConsultarPorId;
var
  ReturnValue: TItensRateioVO;
begin
  ReturnValue := FItensRateioController.ConsultarPorId(33);
  if(returnvalue <> nil)  then
    check(true,'Rateio pesquisado com sucesso!')
  else
    check(False,'Rateio nao encontrado!');
end;


procedure TestTItensRateioController.TestConsultarPorIdNaoEncontrado;
var
  ReturnValue: TItensRateioVO;
begin
  ReturnValue := FItensRateioController.ConsultarPorId(269);
  if(returnvalue <> nil)  then
    check(False,'Rateio pesquisado com sucesso!')
  else
    check(True,'Rateio nao encontrado!');
end;
initialization
  // Register any test cases with the test runner
  RegisterTest(TestTItensRateioController.Suite);
end.

