unit TestURateioController;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, URateioVO, UCondominioVo, UCondominioController, DBClient, DBXJSON,
  UItensRateioController, URateioController, DBXCommon, UITENSrateioVO,
  Generics.Collections, Classes, UController, DB, SysUtils, ConexaoBD, SQLExpr;

type
  // Test methods for class TRateioController

  TestTRateioController = class(TTestCase)
  strict private
    FRateioController: TRateioController;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestConsultarPorId;
    procedure TestConsultarPorIdNaoEncontrado;

  end;

implementation

procedure TestTRateioController.SetUp;
begin
  FRateioController := TRateioController.Create;
end;

procedure TestTRateioController.TearDown;
begin
  FRateioController.Free;
  FRateioController := nil;
end;

procedure TestTRateioController.TestConsultarPorId;
var
  ReturnValue: TRateioVO;
begin
  ReturnValue := FRateioController.ConsultarPorId(11);
  if(returnvalue <> nil)  then
    check(true,'Rateio pesquisada com sucesso!')
  else
    check(False,'Rateio nao encontrada!');
end;


procedure TestTRateioController.TestConsultarPorIdNaoEncontrado;
var
  ReturnValue: TRateioVO;
begin
  ReturnValue := FRateioController.ConsultarPorId(69);
  if(returnvalue <> nil)  then
    check(False,'Rateio pesquisada com sucesso!')
  else
    check(True,'Rateio nao encontrado!');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTRateioController.Suite);
end.

